# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3fdc529086a38a753f8430f111d722de"
name = "cross-cart-app"
handle = "cross-cart-app-1"
application_url = "https://vista-booking-peterson-recognition.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cross-cart-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vista-booking-peterson-recognition.trycloudflare.com/auth/callback",
  "https://vista-booking-peterson-recognition.trycloudflare.com/auth/shopify/callback",
  "https://vista-booking-peterson-recognition.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
